version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432

  backend:
    env_file:
      - ./Backend/.env.docker
    build:
      context: ./Backend
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./Frontend
    ports:
      - 80:80
