import { Grid } from "@mui/material";
import UserCard from "./UserCard";
import { getGames } from "../api/api.endpoints";
import { User, Game, Gender, Region, Platform } from "../api/types";

const games: Game[] = await getGames(5);

const users: User[] = [
  {
    username: "itamarthedoggggg",
    password: "123",
    email: "itamar@gmail.com",
    dob: new Date(1995, 7, 25),
    created_at: new Date(),
    languages: ["Hebrew", "English"],
    country: "Israel",
    gender: Gender.Male,
    bio: "good player",
    rating: 2,
    rating_count: 1,
    discord: "weh",
    avatar: "//images.igdb.com/igdb/image/upload/t_logo_med/co7q89.jpg",
    preferences: {
      games: games,
      region: Region.EUROPE,
      voice: true,
      platform: [Platform.Playstation, Platform.Xbox],
      teammate_platform: [Platform.Playstation, Platform.Xbox],
      preferred_gender: Gender.Both,
      min_age: 24,
      max_age: 30,
    },
  },
  {
    username: "itamarthedog",
    password: "123",
    email: "itamar@gmail.com",
    dob: new Date(1995, 7, 25),
    created_at: new Date(),
    languages: ["Hebrew", "English"],
    country: "Israel",
    gender: Gender.Male,
    bio: "good player",
    rating: 2,
    rating_count: 1,
    discord: "weh",
    avatar: "//images.igdb.com/igdb/image/upload/t_logo_med/co7q89.jpg",
    preferences: {
      games: games,
      region: Region.EUROPE,
      voice: true,
      platform: [Platform.Playstation, Platform.Xbox],
      teammate_platform: [Platform.Playstation, Platform.Xbox],
      preferred_gender: Gender.Both,
      min_age: 24,
      max_age: 30,
    },
  },
  {
    username: "itamarthedog",
    password: "123",
    email: "itamar@gmail.com",
    dob: new Date(1995, 7, 25),
    created_at: new Date(),
    languages: ["Hebrew", "English"],
    country: "Israel",
    gender: Gender.Male,
    bio: "good player",
    rating: 2,
    rating_count: 1,
    discord: "weh",
    avatar: "//images.igdb.com/igdb/image/upload/t_logo_med/co7q89.jpg",
    preferences: {
      games: games,
      region: Region.EUROPE,
      voice: true,
      platform: [Platform.Playstation, Platform.Xbox],
      teammate_platform: [Platform.Playstation, Platform.Xbox],
      preferred_gender: Gender.Both,
      min_age: 24,
      max_age: 30,
    },
  },
  {
    username: "itamarthedog",
    password: "123",
    email: "itamar@gmail.com",
    dob: new Date(1995, 7, 25),
    created_at: new Date(),
    languages: ["Hebrew", "English"],
    country: "Israel",
    gender: Gender.Male,
    bio: "good player",
    rating: 2,
    rating_count: 1,
    discord: "weh",
    avatar: "//images.igdb.com/igdb/image/upload/t_logo_med/co7q89.jpg",
    preferences: {
      games: games,
      region: Region.EUROPE,
      voice: true,
      platform: [Platform.Playstation, Platform.Xbox],
      teammate_platform: [Platform.Playstation, Platform.Xbox],
      preferred_gender: Gender.Both,
      min_age: 24,
      max_age: 30,
    },
  },
  {
    username: "itamarthedog",
    password: "123",
    email: "itamar@gmail.com",
    dob: new Date(1995, 7, 25),
    created_at: new Date(),
    languages: ["Hebrew", "English"],
    country: "Israel",
    gender: Gender.Male,
    bio: "good player",
    rating: 2,
    rating_count: 1,
    discord: "weh",
    avatar: "//images.igdb.com/igdb/image/upload/t_logo_med/co7q89.jpg",
    preferences: {
      games: games,
      region: Region.EUROPE,
      voice: true,
      platform: [Platform.Playstation, Platform.Xbox],
      teammate_platform: [Platform.Playstation, Platform.Xbox],
      preferred_gender: Gender.Both,
      min_age: 24,
      max_age: 30,
    },
  },
  {
    username: "itamarthedog",
    password: "123",
    email: "itamar@gmail.com",
    dob: new Date(1995, 7, 25),
    created_at: new Date(),
    languages: ["Hebrew", "English"],
    country: "Israel",
    gender: Gender.Male,
    bio: "good player",
    rating: 2,
    rating_count: 1,
    discord: "weh",
    avatar: "//images.igdb.com/igdb/image/upload/t_logo_med/co7q89.jpg",
    preferences: {
      games: games,
      region: Region.EUROPE,
      voice: true,
      platform: [Platform.Playstation, Platform.Xbox],
      teammate_platform: [Platform.Playstation, Platform.Xbox],
      preferred_gender: Gender.Both,
      min_age: 24,
      max_age: 30,
    },
  },
  {
    username: "itamarthedog",
    password: "123",
    email: "itamar@gmail.com",
    dob: new Date(1995, 7, 25),
    created_at: new Date(),
    languages: ["Hebrew", "English"],
    country: "Israel",
    gender: Gender.Male,
    bio: "good player",
    rating: 2,
    rating_count: 1,
    discord: "weh",
    avatar: "//images.igdb.com/igdb/image/upload/t_logo_med/co7q89.jpg",
    preferences: {
      games: games,
      region: Region.EUROPE,
      voice: true,
      platform: [Platform.Playstation, Platform.Xbox],
      teammate_platform: [Platform.Playstation, Platform.Xbox],
      preferred_gender: Gender.Both,
      min_age: 24,
      max_age: 30,
    },
  },
  {
    username: "itamarthedog",
    password: "123",
    email: "itamar@gmail.com",
    dob: new Date(1995, 7, 25),
    created_at: new Date(),
    languages: ["Hebrew", "English"],
    country: "Israel",
    gender: Gender.Male,
    bio: "good player",
    rating: 2,
    rating_count: 1,
    discord: "weh",
    avatar: "//images.igdb.com/igdb/image/upload/t_logo_med/co7q89.jpg",
    preferences: {
      games: games,
      region: Region.EUROPE,
      voice: true,
      platform: [Platform.Playstation, Platform.Xbox],
      teammate_platform: [Platform.Playstation, Platform.Xbox],
      preferred_gender: Gender.Both,
      min_age: 24,
      max_age: 30,
    },
  },
];

const UserCards = () => {
  return (
    <Grid className="flex justify-center flex-wrap mb-32 size-full">
      {users.map((user, i) => (
        <Grid item key={i} m={1} mb={20} className="size-80">
          <UserCard user={user} />
        </Grid>
      ))}
    </Grid>
  );
};

export default UserCards;
